title: Rails 5.1 API with Webpacker React Front End
email: tamara@tamouse.org
description: >-
  An example using the new (April 2017) version of Rails 5.1 with
  webpacker making a React.JS front end.
baseurl: "/r5api-react-starter" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tamouse
github_username:  tamouse

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
