title: Rails 5.1 API with Webpacker React Front End
email: tamara@tamouse.org
description: >-
  See the repo at https://github.com/tamouse/r5api-react-starter
baseurl: "/r5api-react-starter" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tamouse
github_username:  tamouse

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
